### ISSUE TITLE
run cyfon.sh error

### ISSUE THREAD

**Issue by s-ebaid** [jonathandata1/cyfon#1]
I get this error when I run cyfon.sh
$sh cyfon.sh                                                                                                                                     
   _cyfon.sh: 60: Bad substitution
   cyfon.sh: 71: Syntax error: "(" unexpected_

i open cyfon.sh 
and line 60 is
__dir="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"

line 71 contain
 function ctrl_c() {
            echo
            echo "Ctrl-C Ended the Application"
            # do the jobs
            exit
    }

**Comment by jonathandata1** [comment]
minor release  for linux will be completed in a few hours, thanks for issue submission

**Comment by jonathandata1** [comment]
this has been resolved now!
