### ISSUE TITLE
Output is MEssy, try to implement something which allows to search for sensitive stuff from all output

### ISSUE THREAD

**Issue by conorxx1** [jonathandata1/cyfon#2]
Cyfon is very powerfull but the output generated is messy especially when not on fish terminal. You can take all the seperate output files and cat it into single file separated by ########## deliminator for subdomain scrape and wget module.

In simple words, make the output bit more readable it's very hard to like cat each file and read individually as there's no support for GUI on VPS.

**Comment by jonathandata1** [comment]
## Method 0 : Pull all files in all subdomains

> I do agree that the information could be organized better, and I plan on seperating all document types and file types in the very near future.

> ## Example: pdfs, docs, zip, php, asp, ect... will all be grouped

> ## _I think what you are ultimately wanting is for the program to pull out all the possible vulnerabilities based off of keywords such as API_KEY, username, password, or any code comments that might be useful, and if so this is my plan, and will require lots of logic._

> I will initially write the logic, but I hope the community will help make it more robust over time. This is one of those feature requests that is on my high priority list, I know there are several companies doing this and they charge A LOT, and if we can have the community build onto the inital algorithm we can really start a free security tools movement.I will initially write the logic, but I hope the community will help make it more robust over time. This is one of those feature requests that is on my high priority list, I know there are several companies doing this and they charge A LOT, and if we can have the community build onto the inital algorithm we can really start a free security tools movement.I will initially write the logic, but I hope the community will help make it more robust over time. This is one of those feature requests that is on my high priority list, I know there are several companies doing this and they charge A LOT, and if we can have the community build onto the inital algorithm we can really start a free security tools movement.I will initially write the logic, but I hope the community will help make it more robust over time. This is one of those feature requests that is on my high priority list, I know there are several companies doing this and they charge A LOT, and if we can have the community build onto the inital algorithm we can really start a free security tools movement.


## Method 1 : Wget Master 1 - Pull all urls from a webpage
>The wget logs are really clean, and have a numbered list, if you are not seeing this let me know. It's been tested on MacOS and Ubuntu 20.04 without using FISH shell (I know FISH can skew things sometimes) 

>### Maybe do a [git pull] because I know the issue you were talking about existed in Version 1.0 of CyFon Tools

>### The log file is generated everytime you run any of the methods, and a directory name is created with the following values


> #### URL+SESSIONID+DATE+TIME/URL+DATE+TIME[.log]


> cyfon/wget_tools/LOGS/CYFON/METHODS/1/LOGS/att.com_8516AC8E-9005-4665-B36C-CFC780DB13A2_Wed-Aug-04-2021-09_39_59-CDT/att.com_Wed-Aug-04-2021-09_39_59-CDT.log


-      1	http://idp-content-orchestration.com-att-idp.svc.cluster.local
-      2	http://instagram.com/att/
-      3	http://schema.org
-      4	http://www.w3.org/2000/svg
-      5	https://about.att.com/newsroom/2021/summer_learning_academy.html
-      6	https://att.demdex.net
-      7	https://att.mpeasylink.com/mpel/mpel.js
-      8	https://att.p.delivery.net/m/p/att/api_capture/process.asp
-      9	https://attservicesinc.tt.omtrdc.net
-     10	https://dpm.demdex.net
-     11	https://privacy-policy.truste.com
-     12	https://s.go-mpulse.net/boomerang/
-     13	https://s2.go-mpulse.net/boomerang/
-     14	https://smetrics.att.com
-     15	https://twitter.com/att
-     16	https://www.att.com
-     17	https://www.att.com/
-     18	https://www.att.com/5Gforyou
-     19	https://www.att.com/5g/consumer/
-     20	https://www.att.com/deals/
-     21	https://www.att.com/directv/
-     22	https://www.att.com/ecms/dam/att/consumer/global/logos/att_globe_500x500.jpg
-     23	https://www.att.com/es-us/
-     24	https://www.att.com/global-search/search
-     25	https://www.att.com/global-search/search.jsp?q={search_term}
-     26	https://www.att.com/internet/
-     27	https://www.att.com/prepaid/
-     28	https://www.att.com/scripts/adobe/prod/mbox-contents.js
-     29	https://www.att.com/shopcms/media/att/2014/global/social-logo/logo-att-color-trans-200x200.png
-     30	https://www.att.com/smallbusiness/explore/index.html?bref=IBBz250012babsbzL
-     31	https://www.att.com/support/
-     32	https://www.att.com/tv/
-     33	https://www.att.com/tv/device-features/
-     34	https://www.att.com/wireless/
-     35	https://www.att.com/wireless/right-to-you/
-     36	https://www.bing.com
-     37	https://www.dynatrace.com/company/trust-center/customers/reports/*/
-     38	https://www.facebook.com/ATT
-     39	https://www.linkedin.com/company/at
-     40	https://www.linkedin.com/company/at&t
-     41	https://www.youtube.com/user/ShareATT
